[build]
  publish = "dist"
  command = "bash netlify-build.sh"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8.19.3"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 